### ISSUE TITLE
Multiple Readers

### ISSUE THREAD

**Issue by s00500** [jrnas/wn-smartmeter#75]
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/ludeeus/integration_blueprint/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Hey there, I have multiple readers on my logwien accound and I am trying to add them as seperate integrations. this works fine, but afterwards the numbers reported by these entity suddenly sync up and report the same on the different enteties

### Describe the solution you'd like

Fix the problem

### Describe alternatives you've considered

Other alternatives: I could use espglow

### Additional context

Not sure I am a massive fan of the issue template ;-)

If there is any way I can help testing of developing on this let me know :-)

**Comment by jrnas** [comment]
please be patient, i will try to reproduce that error

**Comment by jrnas** [comment]
ok i cannot reproduce that error, i added two different meter readers, 
please delete both and recreate it and dont touch the entities ids and try it again.
and please give me info how long does it take that different entities sync up..

**Comment by jrnas** [comment]
fixed with latest 2.0.8

**Comment by s00500** [comment]
Hey @jrnas 
Super awesome, i am on a bussinesstrip this week but I will certainly test when back home, thanks a lot!!!

**Comment by s00500** [comment]
Awesome, this works!

**Comment by s00500** [comment]
Hm... I actually still have this issue...

2.0.9 is the version I am on...
